import Head from 'next/head'
import HeroImage from '../components/Homepage/HeroImage/HeroImage'
import HeroSection from '../components/Homepage/HeroSection/HeroSection'
import Navbar from '../components/Homepage/Navbar/Navbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Bright Local SEO | MongoDB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Components goes here */}
      <Navbar />
      <HeroSection />
      <HeroImage />
    </div>
  )
}
